const imageUrl = (id) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=700&h=500&fit=crop`;

const products = [
  {
    id: '1',
    naziv: 'Drvene kocke',
    slika: imageUrl('12955537'),
    opis: 'Šarene drvene kocke za slaganje, brojanje i učenje prvih oblika.',
    cijena: 24.99,
    kategorija: 'Edukativne igračke',
    uzrast: '2+ godine',
    materijal: 'Drvo',
    brojNaStanju: 18,
    rating: 4.5,
  },
  {
    id: '2',
    naziv: 'Muzički ksilofon',
    slika: imageUrl('6743138'),
    opis: 'Drveni ksilofon u boji za prve melodije, ritam i razvoj sluha.',
    cijena: 28.5,
    kategorija: 'Muzičke igračke',
    uzrast: '3+ godine',
    materijal: 'Drvo i metal',
    brojNaStanju: 11,
    rating: 4,
  },
  {
    id: '3',
    naziv: 'Puzzle životinje',
    slika: imageUrl('7296376'),
    opis: 'Slagalica sa životinjama koja razvija pažnju, strpljenje i motoriku.',
    cijena: 15.99,
    kategorija: 'Puzzle',
    uzrast: '4+ godine',
    materijal: 'Karton',
    brojNaStanju: 14,
    rating: 4,
  },
  {
    id: '4',
    naziv: 'Plišani medo',
    slika: imageUrl('16272040'),
    opis: 'Mekani plišani medo za igru, spavanje i prve dječije avanture.',
    cijena: 19.5,
    kategorija: 'Plišane igračke',
    uzrast: '0+ mjeseci',
    materijal: 'Pliš',
    brojNaStanju: 25,
    rating: 5,
  },
  {
    id: '5',
    naziv: 'Plišani zeko',
    slika: imageUrl('4887208'),
    opis: 'Nježni plišani zeka u pastelnim bojama za maženje i igru.',
    cijena: 18.99,
    kategorija: 'Plišane igračke',
    uzrast: '0+ mjeseci',
    materijal: 'Pliš',
    brojNaStanju: 17,
    rating: 4.5,
  },
  {
    id: '6',
    naziv: 'Set za crtanje',
    slika: imageUrl('459799'),
    opis: 'Set bojica za male umjetnike koji vole crtanje, bojenje i stvaranje.',
    cijena: 13.99,
    kategorija: 'Kreativne igračke',
    uzrast: '5+ godina',
    materijal: 'Drvo i pigment',
    brojNaStanju: 16,
    rating: 5,
  },
  {
    id: '7',
    naziv: 'Plastelin za djecu',
    slika: imageUrl('2425817'),
    opis: 'Mekani plastelin u više boja za oblikovanje, igru i razvoj motorike.',
    cijena: 11.99,
    kategorija: 'Kreativne igračke',
    uzrast: '3+ godine',
    materijal: 'Plastelin',
    brojNaStanju: 21,
    rating: 4.5,
  },
  {
    id: '8',
    naziv: 'Autić trkač',
    slika: imageUrl('4488181'),
    opis: 'Brzi dječiji autić za trke, guranje i veselu igru na podu.',
    cijena: 24.99,
    kategorija: 'Vozila',
    uzrast: '3+ godine',
    materijal: 'Plastika',
    brojNaStanju: 30,
    rating: 4.5,
  },
  {
    id: '9',
    naziv: 'Dječiji voz',
    slika: imageUrl('9872966'),
    opis: 'Drveni voz sa šinama za slaganje pruge i kreativnu igru.',
    cijena: 34.99,
    kategorija: 'Vozila',
    uzrast: '3+ godine',
    materijal: 'Drvo',
    brojNaStanju: 9,
    rating: 4.5,
  },
  {
    id: '10',
    naziv: 'Društvena igra Memorija',
    slika: imageUrl('7943699'),
    opis: 'Igra memorije sa karticama za zabavu, koncentraciju i vježbanje pažnje.',
    cijena: 21.99,
    kategorija: 'Društvene igre',
    uzrast: '4+ godine',
    materijal: 'Karton',
    brojNaStanju: 20,
    rating: 4.5,
  },
  {
    id: '11',
    naziv: 'Čovječe ne ljuti se',
    slika: imageUrl('11646952'),
    opis: 'Klasična porodična igra sa figuricama, kockicom i puno smijeha.',
    cijena: 16.99,
    kategorija: 'Društvene igre',
    uzrast: '5+ godina',
    materijal: 'Karton i plastika',
    brojNaStanju: 13,
    rating: 4,
  },
  {
    id: '12',
    naziv: 'Lopta duginih boja',
    slika: imageUrl('8455910'),
    opis: 'Lagana šarena lopta za igru u dvorištu, parku ili dječijoj sobi.',
    cijena: 9.99,
    kategorija: 'Sportske igračke',
    uzrast: '2+ godine',
    materijal: 'Guma',
    brojNaStanju: 22,
    rating: 3.5,
  },
];

export default products;
